spring:
  cloud:
    config:
      server:
        git:
          searchPaths: '{profile}'
        bootstrap: false # 已自行装配bean,勿设置为true
  profiles:
    active: db # db:使用自定义的配置仓库  git: 使用git作为配置仓库
feign:
  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000
choerodon:
  config:
    server:
      manager-service: manager-service
      notify-endpoint: /choerodon/config
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registryFetchIntervalSeconds: 10

